# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 30, 868, 814))
        self.layoutWidget.setObjectName("layoutWidget")
        self.plotLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.plotLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem, 0, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 400, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.plotLayout.addItem(spacerItem3, 5, 1, 1, 1)
        self.plot3 = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot3.sizePolicy().hasHeightForWidth())
        self.plot3.setSizePolicy(sizePolicy)
        self.plot3.setMinimumSize(QtCore.QSize(400, 400))
        self.plot3.setObjectName("plot3")
        self.plotLayout.addWidget(self.plot3, 0, 5, 1, 1)
        self.plot4 = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot4.sizePolicy().hasHeightForWidth())
        self.plot4.setSizePolicy(sizePolicy)
        self.plot4.setMinimumSize(QtCore.QSize(400, 400))
        self.plot4.setObjectName("plot4")
        self.plotLayout.addWidget(self.plot4, 5, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 400, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.plotLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.plot1 = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot1.sizePolicy().hasHeightForWidth())
        self.plot1.setSizePolicy(sizePolicy)
        self.plot1.setMinimumSize(QtCore.QSize(400, 400))
        self.plot1.setMaximumSize(QtCore.QSize(449, 16777215))
        self.plot1.setObjectName("plot1")
        self.plotLayout.addWidget(self.plot1, 0, 2, 1, 1)
        self.plot2 = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot2.sizePolicy().hasHeightForWidth())
        self.plot2.setSizePolicy(sizePolicy)
        self.plot2.setMinimumSize(QtCore.QSize(400, 400))
        self.plot2.setObjectName("plot2")
        self.plotLayout.addWidget(self.plot2, 5, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.plotLayout.addItem(spacerItem5, 1, 3, 2, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 195, 103))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.logLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.logLayout.setContentsMargins(0, 0, 0, 0)
        self.logLayout.setObjectName("logLayout")
        self.logComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.logComboBox.setObjectName("logComboBox")
        self.logLayout.addWidget(self.logComboBox, 0, 1, 1, 1)
        self.startDateEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startDateEdit.sizePolicy().hasHeightForWidth())
        self.startDateEdit.setSizePolicy(sizePolicy)
        self.startDateEdit.setObjectName("startDateEdit")
        self.logLayout.addWidget(self.startDateEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.logLayout.addWidget(self.label, 1, 0, 1, 1)
        self.endDateEdit = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endDateEdit.sizePolicy().hasHeightForWidth())
        self.endDateEdit.setSizePolicy(sizePolicy)
        self.endDateEdit.setObjectName("endDateEdit")
        self.logLayout.addWidget(self.endDateEdit, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.logLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.LogButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogButton.sizePolicy().hasHeightForWidth())
        self.LogButton.setSizePolicy(sizePolicy)
        self.LogButton.setObjectName("LogButton")
        self.logLayout.addWidget(self.LogButton, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 21))
        self.menubar.setObjectName("menubar")
        self.menuSensors = QtWidgets.QMenu(self.menubar)
        self.menuSensors.setObjectName("menuSensors")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSensors.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Start date"))
        self.label_2.setText(_translate("MainWindow", "End date"))
        self.LogButton.setText(_translate("MainWindow", "Open log file"))
        self.menuSensors.setTitle(_translate("MainWindow", "Sensors"))


