# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 3, 907, 929))
        self.widget.setObjectName("widget")
        self.plotLayout = QtWidgets.QGridLayout(self.widget)
        self.plotLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.plotLayout.addWidget(self.label, 8, 1, 1, 1)
        self.LogButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogButton.sizePolicy().hasHeightForWidth())
        self.LogButton.setSizePolicy(sizePolicy)
        self.LogButton.setObjectName("LogButton")
        self.plotLayout.addWidget(self.LogButton, 2, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.plotLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.plot4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot4.sizePolicy().hasHeightForWidth())
        self.plot4.setSizePolicy(sizePolicy)
        self.plot4.setMinimumSize(QtCore.QSize(400, 400))
        self.plot4.setObjectName("plot4")
        self.plotLayout.addWidget(self.plot4, 6, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.plotLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.plot3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot3.sizePolicy().hasHeightForWidth())
        self.plot3.setSizePolicy(sizePolicy)
        self.plot3.setMinimumSize(QtCore.QSize(400, 400))
        self.plot3.setObjectName("plot3")
        self.plotLayout.addWidget(self.plot3, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem2, 1, 6, 1, 1)
        self.logComboBox = QtWidgets.QComboBox(self.widget)
        self.logComboBox.setObjectName("logComboBox")
        self.plotLayout.addWidget(self.logComboBox, 5, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.plotLayout.addItem(spacerItem3, 6, 5, 1, 1)
        self.TimeScaleSlider = QtWidgets.QSlider(self.widget)
        self.TimeScaleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TimeScaleSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.TimeScaleSlider.setObjectName("TimeScaleSlider")
        self.plotLayout.addWidget(self.TimeScaleSlider, 7, 1, 1, 1)
        self.plot1 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot1.sizePolicy().hasHeightForWidth())
        self.plot1.setSizePolicy(sizePolicy)
        self.plot1.setMinimumSize(QtCore.QSize(400, 400))
        self.plot1.setMaximumSize(QtCore.QSize(449, 16777215))
        self.plot1.setObjectName("plot1")
        self.plotLayout.addWidget(self.plot1, 1, 1, 1, 1)
        self.plot2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot2.sizePolicy().hasHeightForWidth())
        self.plot2.setSizePolicy(sizePolicy)
        self.plot2.setMinimumSize(QtCore.QSize(400, 400))
        self.plot2.setObjectName("plot2")
        self.plotLayout.addWidget(self.plot2, 6, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.UpdateButton = QtWidgets.QPushButton(self.widget)
        self.UpdateButton.setObjectName("UpdateButton")
        self.plotLayout.addWidget(self.UpdateButton, 8, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.plotLayout.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.plotLayout.addItem(spacerItem6, 9, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuSensors = QtWidgets.QMenu(self.menubar)
        self.menuSensors.setObjectName("menuSensors")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSensors.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Time Frame"))
        self.LogButton.setText(_translate("MainWindow", "Open log file"))
        self.UpdateButton.setText(_translate("MainWindow", "Update"))
        self.menuSensors.setTitle(_translate("MainWindow", "Sensors"))

